# Generated by Django 5.1.4 on 2024-12-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images/')),
                ('thumbnail_samll', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumbnail_medium', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumbnail_large', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
