# Generated by Django 5.1.4 on 2024-12-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_imagemodel_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='thumbnail_samll',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='thumbnail_large',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='thumbnail_medium',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
